inherit_from:
  - '.rubocop_core.yml'

# Put your project-specifc Rubocop config here

Style/ExtraSpacing:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/ruby-progressbar.rb'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IndentationWidth:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled:                   true
  EnforcedStyleForMultiline: 'no_comma'
